
nominatim:
    email: "your@email.org"
    # endpoint, the place where Nominatim is running, for example http://open.mapquestapi.com/nominatim/v1
    service_url: http://open.mapquestapi.com/nominatim/v1

error_email:
    email: "nyan@desu.fi"
    sender_email: "example_address@foo.bar"
    server: "localhost"
    port: 25
    #username:
    #password:
    #method: :plain